name: spec-up-render
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-spec:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build Spec-Up 🔧
        run: |
          npm install
          npm run render
          mkdir -p ./dist/api-docs

      - name: Build API Documentation 📚
        run: |
          # Install redoc-cli and swagger-cli
          npm install -g redoc-cli swagger-cli

          # Copy OpenAPI specs to working directory
          cp -r playground/trust-registry/api/* ./

          # Validate OpenAPI specs
          swagger-cli validate trqp.yaml

          # Build Redoc documentation
          redoc-cli bundle trqp.yaml -o ./dist/api-docs/redoc.html --title "Ayra TRQP API Documentation"

          # Create Swagger UI documentation
          mkdir -p ./dist/api-docs/swagger-ui
          wget -O ./dist/api-docs/swagger-ui/swagger-ui-bundle.js https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui-bundle.js
          wget -O ./dist/api-docs/swagger-ui/swagger-ui.css https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui.css

          # Create Swagger UI HTML
          cat > ./dist/api-docs/swagger-ui/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Ayra TRQP API Documentation</title>
            <link rel="stylesheet" href="swagger-ui.css" />
          </head>
          <body>
            <div id="swagger-ui"></div>
            <script src="swagger-ui-bundle.js"></script>
            <script>
              window.onload = function() {
                window.ui = SwaggerUIBundle({
                  url: "../trqp.yaml",
                  dom_id: '#swagger-ui',
                  deepLinking: true,
                  presets: [SwaggerUIBundle.presets.apis],
                });
              };
            </script>
          </body>
          </html>
          EOL

          # Copy OpenAPI specs to dist directory
          cp trqp.yaml ./dist/api-docs/

          # Create index page linking to both documentation types
          cat > ./dist/api-docs/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Ayra TRQP API Documentation</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
              h1 { color: #333; }
              .docs-container { display: flex; gap: 20px; margin-top: 30px; }
              .doc-option { 
                flex: 1; 
                padding: 20px; 
                border: 1px solid #ddd; 
                border-radius: 8px;
                text-align: center;
              }
              .doc-option h2 { margin-top: 0; }
              .doc-option a { 
                display: inline-block;
                margin-top: 15px;
                padding: 10px 20px;
                background-color: #0066cc;
                color: white;
                text-decoration: none;
                border-radius: 4px;
              }
              .doc-option a:hover { background-color: #0055aa; }
            </style>
          </head>
          <body>
            <h1>Ayra TRQP API Documentation</h1>
            <p>Choose your preferred documentation format:</p>
            
            <div class="docs-container">
              <div class="doc-option">
                <h2>ReDoc</h2>
                <p>Clean, responsive, and easy-to-read API documentation.</p>
                <a href="redoc.html">Open ReDoc</a>
              </div>
              
              <div class="doc-option">
                <h2>Swagger UI</h2>
                <p>Interactive documentation with try-it-out capability.</p>
                <a href="swagger-ui/index.html">Open Swagger UI</a>
              </div>
            </div>
            
            <div style="margin-top: 30px">
              <h3>Raw OpenAPI Specification</h3>
              <p>You can also access the raw OpenAPI specification file:</p>
              <ul>
                <li><a href="trqp.yaml">OpenAPI Specification (YAML)</a></li>
              </ul>
            </div>
          </body>
          </html>
          EOL

          # Add link to API docs from main index
          echo '<div style="margin-top: 40px; padding: 20px; background-color: #f5f5f5; border-radius: 8px;">' >> ./dist/index.html
          echo '<h2>API Documentation</h2>' >> ./dist/index.html
          echo '<p>View the Ayra Trust Registry API documentation:</p>' >> ./dist/index.html
          echo '<p><a href="api-docs/" style="font-weight: bold; color: #0066cc;">Open API Documentation</a></p>' >> ./dist/index.html
          echo '</div>' >> ./dist/index.html

          # Clean up temporary files
          rm -f trqp.yaml

      - name: Clean up 🧹
        run: |
          rm -rf node_modules

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
          allow_empty_commit: true
          force_orphan: true
