name: Test Docker Build

on:
  push:
    branches: [main]
    paths:
      - "playground/**"
  pull_request:
    branches: [main]
    paths:
      - "playground/**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose
        run: |
          cd playground
          docker compose build
